service: golang-linechatbot-on-lambda

frameworkVersion: '2'

provider:
  name: aws
  runtime: go1.x
  environment:
    CSECRET: YOU_LINE_CHANNEL_SECRET
    BTOKEN: YOU_LINE_CHANNEL_ACCESS_TOKEN
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "translate:TranslateText"
        - "comprehend:DetectDominantLanguage"
      Resource: "*"

  package:
    exclude:
      - ./**
    include:
      - ./bin/**

functions:
  LiaoLiao:
    handler: bin/LiaoLiao
    events:
      - http:
          path: LiaoLiao
          method: post